# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-10 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('delhi', 'Delhi'), ('bangalore', 'Bangalore'), ('chennai', 'Chennai')], max_length=200)),
                ('destination', models.CharField(choices=[('delhi', 'Delhi'), ('bangalore', 'Bangalore'), ('chennai', 'Chennai')], max_length=200)),
                ('truck_type', models.CharField(choices=[('flatbed Truck', 'Flatbed Truck'), ('garbage Truck', 'Garbage Truck'), ('dump Truck', 'Dump Truck')], max_length=200)),
                ('Date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
